version: '2'
services:
  sort:
    build: sort
    volumes:
      - data-sort:/tmp
  sysbench:
    build: sysbench
  mysql:
    build: mysql
    volumes:
      - data-mysql:/var/lib/mysql
  influxdb:
    image: influxdb:latest
  collector:
    build: collector
    command: [ "--influx", "--influxdbhost=influxdb" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
volumes:
  data-sort:
  data-mysql:
