version: '2'
services:
  sort:
    build: sort
    volumes:
      - data-sort:/tmp
  sysbench:
    build: sysbench
  mysql:
    build: mysql
    volumes:
      - data-mysql:/var/lib/mysql
  influxdb:
    image: influxdb:latest
    volumes:
      - data-influxdb-var-lib:/var/lib/grafana
      - data-influxdb-var-log:/var/log/grafana
      - data-influxdb-etc:/etc/grafana
  collector:
    build: collector
    command: [ "--influx", "--influxdbhost=influxdb" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
volumes:
  data-sort:
  data-mysql:
  data-influxdb-var-lib:
  data-influxdb-var-log:
  data-influxdb-etc:
