version: '2'
services:
  gensort:
    build: gensort
    command: [ "100000000" ]
    volumes:
      - data-sort:/tmp
  sysbench:
    build: sysbench
    command: [ "prepare" ]
    links:
      - mysql
  mysql:
    build: mysql
    volumes:
      - data:/var/lib/mysql
volumes:
  data-sort:
  data:
