version: '2'
services:
  sysbench:
    build: sysbench
    command: [ "run" ]
    links:
      - mysql
      - influxdb
  mysql:
    build: mysql
    volumes:
      - data:/var/lib/mysql
    mem_limit: 1G
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '27mb'
      device_write_bps:
        - path: /dev/sda
          rate: '27mb'
  influxdb:
    image: influxdb:latest
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    links:
      - influxdb
volumes:
  data: